spring:
  application:
    name: ms-observability
    
server:
  port: 8085
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,beans,env
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    tags:
      application: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

logging:
  level:
    ec.edu.espe.observability: DEBUG
    org.springframework.cloud.openfeign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/observability.log

# Custom monitoring configuration
monitoring:
  services:
    check-interval: 30s
    timeout: 5s
  alerts:
    enabled: true
    threshold:
      response-time: 2000ms
      error-rate: 5
