server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Server Routes (sin autenticación)
        - id: auth-server
          uri: lb://ms-auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        # Publicaciones Routes (requieren autenticación)
        - id: publicaciones-autores
          uri: lb://api-publicaciones
          predicates:
            - Path=/api/v1/autores/**
          filters:
            - StripPrefix=2
            - name: JwtAuthenticationFilter
        - id: publicaciones-libros
          uri: lb://api-publicaciones
          predicates:
            - Path=/api/v1/libros/**
          filters:
            - StripPrefix=2
            - name: JwtAuthenticationFilter
        # OpenAI Routes (requieren autenticación)
        - id: openai-service
          uri: lb://ms-openai
          predicates:
            - Path=/api/v1/openai/**
          filters:
            - StripPrefix=2
            - name: JwtAuthenticationFilter
        # Notificaciones Routes (requieren autenticación)
        - id: notificaciones-service
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/v1/notificaciones/**
          filters:
            - StripPrefix=2
            - name: JwtAuthenticationFilter
        # SOAP Routes (requieren autenticación)
        - id: soap-service
          uri: lb://soap
          predicates:
            - Path=/api/v1/soap/**
          filters:
            - StripPrefix=2
            - name: JwtAuthenticationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    ec.edu.espe.gateway: DEBUG
