server:
  port: 0

spring:
  application:
    name: api-publicaciones
  datasource:
    #url: jdbc:postgresql://localhost:5432/publicaciones_db
    #username: postgres
    #password: qwerty123
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26257/publicaciones_db?sslmode=disable
    username: root
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

# Configuración para procesamiento de eventos Outbox
outbox:
  job:
    enabled: true
    fixed-delay: 10000  # 10 segundos
    cleanup-delay: 3600000  # 1 hora
    max-retry-attempts: 5
    retention-days: 7

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.amqp: DEBUG
    publicaciones: DEBUG
    root: INFO

info:
  app:
    name: "API Publicaciones - Sistema Editorial"
    version: "1.0.0"
    description: "Microservicio para gestión de publicaciones científicas con ciclo de vida editorial completo"
    author: "Geovanny Cudco"
    features:
      - "Gestión de Autores y Publicaciones (Libros/Artículos)"
      - "Ciclo de vida editorial: BORRADOR → EN_REVISION → APROBADO → PUBLICADO"
      - "Control de versiones"
      - "Eventos de dominio"
      - "Patrón Outbox para eventos distribuidos"
      - "Integración con RabbitMQ"
      - "Seguridad basada en roles JWT"
